# Generated by Django 5.2.1 on 2025-06-29 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 29, 15, 1, 58, 841319, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
